options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/the-mesh-458219-a9/emotionflow/emotionflow:latest',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/the-mesh-458219-a9/emotionflow/emotionflow:latest'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'emotionflow',
      '--image', 'us-central1-docker.pkg.dev/the-mesh-458219-a9/emotionflow/emotionflow:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-secrets', 'OPENAI_API_KEY=OPENAI_API_KEY:latest,MONGODB_URI=MONGODB_URI:latest'
    ]

images:
  - 'us-central1-docker.pkg.dev/the-mesh-458219-a9/emotionflow/emotionflow:latest'
